[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#FFA500"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"

[global]
showWarningOnDirectExecution = false
